# Generated by Django 5.1.1 on 2024-11-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basketballclub",
            old_name="ownerType",
            new_name="creatorType",
        ),
    ]
