# Generated by Django 5.1.1 on 2024-11-03 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0004_scoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoring",
            name="accuracy",
            field=models.DecimalField(decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name="scoring",
            name="attempts",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="scoring",
            name="creatorSaffId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="scoring",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="scoring",
            name="made",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="scoring",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("PA", "pendingApproval"),
                    ("D", "Declined"),
                ],
                default="PA",
                max_length=2,
            ),
        ),
    ]
