# Generated by Django 5.1.1 on 2024-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0005_scoring_accuracy_scoring_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoring",
            name="scoringType",
            field=models.CharField(
                choices=[
                    ("FS", "FreeStyle"),
                    ("3P", "Three Points"),
                    ("CS", "Close Shots"),
                    ("MR", "Mid Range"),
                    ("LU", "Lay Up"),
                    ("FA", "Fade Away"),
                    ("btl", "L-B/W leg Score"),
                    ("btl", "R-B/W leg Score"),
                ],
                default="FS",
                max_length=5,
            ),
        ),
    ]
