# Generated by Django 5.1.1 on 2024-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basketball", "0006_alter_scoring_scoringtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoring",
            name="scoringType",
            field=models.CharField(
                choices=[
                    ("FS", "FreeStyle"),
                    ("3P", "Three Points"),
                    ("CS", "Close Shots"),
                    ("MR", "Mid Range"),
                    ("LU", "Lay Up"),
                    ("FA", "Fade Away"),
                    ("btll", "L-B/W leg Score"),
                    ("btl", "R-B/W leg Score"),
                    ("sgb", "score and go back"),
                    ("1v1", "1v1"),
                ],
                default="FS",
                max_length=5,
            ),
        ),
    ]
