# Generated by Django 5.0.6 on 2024-08-12 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creatorId', models.IntegerField()),
                ('contactName', models.CharField(max_length=100)),
                ('contactPhone', models.IntegerField()),
                ('contactEmail', models.EmailField(max_length=254)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('Address', models.CharField(max_length=1000)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('projectId', models.IntegerField()),
                ('addedby_Id', models.IntegerField()),
                ('addedDate', models.DateField(default=datetime.datetime.now)),
                ('levels', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ponds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('projectId', models.IntegerField()),
                ('position_row', models.IntegerField()),
                ('position_col', models.IntegerField()),
                ('materialType', models.CharField(max_length=100)),
                ('depth', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('createdDate', models.DateField(default=datetime.datetime.now)),
                ('creatorId', models.IntegerField()),
                ('contactName', models.CharField(max_length=100, null=True)),
                ('contactPhone', models.BigIntegerField(null=True)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('country', models.CharField(default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=100, null=True)),
                ('zipCode', models.IntegerField(default='')),
                ('fullsAddress', models.CharField(default='', max_length=1000, null=True)),
                ('area', models.IntegerField(default=0, null=True)),
                ('length', models.IntegerField(default=0, null=True)),
                ('width', models.IntegerField(default=0, null=True)),
                ('Status', models.IntegerField(default=1)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('tiktok', models.CharField(max_length=100, null=True)),
                ('otherOnline', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pondId', models.IntegerField()),
                ('waterLevel', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('averageWeight', models.IntegerField(null=True)),
                ('totalWeight', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('recordDate', models.DateField(default=datetime.datetime.now)),
                ('fishId', models.IntegerField(null=True)),
                ('leadByName', models.IntegerField(null=True)),
                ('assittedByName', models.CharField(max_length=100, null=True)),
                ('assittedById', models.IntegerField(null=True)),
                ('followupTask', models.CharField(max_length=100, null=True)),
                ('followupTaskDueDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('added', models.IntegerField(null=True)),
                ('addedSize', models.IntegerField(null=True)),
                ('addedWeight', models.IntegerField(null=True)),
                ('removed', models.IntegerField(null=True)),
                ('removedSize', models.IntegerField(null=True)),
                ('removedWeight', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
