# Generated by Django 5.0.6 on 2024-08-13 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocking',
            name='followupTaskDueDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='recordDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
