# Generated by Django 5.0.6 on 2024-08-14 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_stocking_followuptaskduedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondstoDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pondId', models.IntegerField()),
                ('pomdName', models.CharField(max_length=100)),
                ('taskName', models.CharField(max_length=100)),
                ('taskId', models.IntegerField()),
                ('createDate', models.DateField(default=datetime.datetime.now)),
                ('dueDate', models.DateField()),
                ('urgency', models.IntegerField()),
                ('status', models.IntegerField()),
                ('completeDate', models.DateField()),
                ('requestorId', models.IntegerField()),
                ('assignedToId', models.IntegerField()),
                ('taskDetails', models.CharField(max_length=1000)),
            ],
        ),
    ]
