# Generated by Django 5.0.6 on 2024-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pondstodolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondstodolist',
            name='assignedToId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pondstodolist',
            name='completeDate',
            field=models.DateField(null=True),
        ),
    ]
