# Generated by Django 5.0.6 on 2024-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pondstodolist_assignedtoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondstodolist',
            name='completeDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pondstodolist',
            name='dueDate',
            field=models.DateTimeField(),
        ),
    ]
