# Generated by Django 5.0.6 on 2024-08-14 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_pondstodolist_completedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondstodolist',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
