# Generated by Django 5.0.6 on 2024-08-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_pondstodolist_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondstodolist',
            name='projectId',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
