# Generated by Django 5.0.6 on 2024-08-14 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pondstodolist_projectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pondId', models.IntegerField()),
                ('projectId', models.IntegerField()),
                ('dateSold', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('fishId', models.IntegerField()),
                ('buyerId', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('paymentBal', models.IntegerField()),
                ('status', models.IntegerField()),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
