# Generated by Django 5.0.6 on 2024-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
