# Generated by Django 5.0.6 on 2024-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sales_weight_alter_sales_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pondId', models.IntegerField()),
                ('feedDateTime', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('reaction', models.CharField(choices=[('H', 'Hyper'), ('N', 'Normal'), ('BE', 'Barely Eating'), ('NE', 'Not Eating')], max_length=2)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pondId', models.IntegerField()),
                ('eventDate', models.DateField()),
                ('depth', models.IntegerField()),
                ('preWaterColor', models.CharField(max_length=100)),
                ('preWaterCond', models.CharField(max_length=600)),
            ],
        ),
    ]
