# Generated by Django 5.0.6 on 2024-09-06 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_feeding_waterchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.IntegerField()),
                ('pondId', models.IntegerField()),
                ('projectId', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('src', models.ImageField(null=True, upload_to='images')),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('uploadDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='activityNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='followupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.IntegerField()),
                ('notificationId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='followupTaskSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityNamesId', models.IntegerField()),
                ('followupNameId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='stocking',
            name='leadById',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='leadByName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
