# Generated by Django 5.0.6 on 2024-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_activitiesimages_activitynames_followuptask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynames',
            name='creatorId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
