# Generated by Django 5.0.6 on 2024-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_activitynames_creatorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('PurchaseId', models.IntegerField()),
                ('farmId', models.IntegerField()),
                ('vendorId', models.IntegerField()),
            ],
        ),
    ]
