# Generated by Django 5.0.6 on 2024-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_stocksource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocking',
            old_name='pondId',
            new_name='fromPondId',
        ),
        migrations.AddField(
            model_name='stocking',
            name='fromVendordId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocking',
            name='toPondId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocking',
            name='toVendorId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
