# Generated by Django 5.0.6 on 2024-09-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_pondid_stocking_frompondid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocking',
            old_name='added',
            new_name='addedQuantity',
        ),
    ]
