# Generated by Django 5.0.6 on 2024-09-16 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_added_stocking_addedquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('managerId', models.IntegerField(null=True)),
                ('dateOfBirth', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('employmentDate', models.DateTimeField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stocking',
            name='addedimage',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
