# Generated by Django 5.0.6 on 2024-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_staff_email_staff_farmid_staff_homeaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='firstName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
