# Generated by Django 5.0.6 on 2024-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_staff_firstname_alter_staff_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='farmId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneMain',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
