# Generated by Django 5.0.6 on 2024-09-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_staff_farmid_alter_staff_phonemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phoneMain',
            field=models.CharField(max_length=100),
        ),
    ]
