# Generated by Django 5.0.6 on 2024-09-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_staff_phonemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phoneSecondary',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
