# Generated by Django 5.0.6 on 2024-09-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_staff_phonesecondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dateOfBirth',
            field=models.DateTimeField(null=True),
        ),
    ]
