# Generated by Django 5.0.6 on 2024-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_staff_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocking',
            name='pondId',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
