# Generated by Django 5.0.6 on 2024-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_stocking_frompondid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pondstodolist',
            name='pomdName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pondstodolist',
            name='taskName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
