# Generated by Django 5.0.6 on 2024-09-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_pondstodolist_pomdname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pondstodolist',
            old_name='projectId',
            new_name='farmId',
        ),
    ]
