# Generated by Django 5.0.6 on 2024-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_rename_projectid_pondstodolist_farmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('creatorId', models.IntegerField(null=True)),
                ('phoneOne', models.IntegerField(null=True)),
                ('phoneTwo', models.IntegerField(null=True)),
                ('emailOne', models.EmailField(max_length=254, null=True)),
                ('emailTwo', models.EmailField(max_length=254, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=1000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmId', models.IntegerField()),
                ('ItemsGroupId', models.IntegerField()),
                ('itemDescription', models.CharField(max_length=500)),
                ('unitCost', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('deliveryCost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField()),
                ('expensesDate', models.DateTimeField()),
                ('paymentToId', models.IntegerField(null=True)),
                ('shopId', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseId', models.IntegerField(null=True)),
                ('sharePecentage', models.IntegerField(null=True)),
                ('allocatedToId', models.IntegerField(null=True)),
                ('ItemsGroupId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
