# Generated by Django 5.0.6 on 2024-09-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_contacts_expenses_expensesdisbursement_itemsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmId', models.IntegerField()),
                ('ItemsGroupId', models.IntegerField()),
                ('itemDescription', models.CharField(max_length=500)),
                ('unitCost', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('deliveryCost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField()),
                ('expensesDate', models.DateTimeField()),
                ('paymentToId', models.IntegerField(null=True)),
                ('shopId', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
