# Generated by Django 5.0.6 on 2024-09-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
