# Generated by Django 5.0.6 on 2024-09-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_delete_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesdisbursement',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
