# Generated by Django 5.0.6 on 2024-09-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_expensesdisbursement_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesdisbursement',
            name='ItemsGroupId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensesdisbursement',
            name='allocatedToId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensesdisbursement',
            name='expenseId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensesdisbursement',
            name='sharePecentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
