# Generated by Django 5.1.1 on 2024-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_expensesdisbursement_itemsgroupid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="brand",
            field=models.CharField(
                choices=[
                    ("IH", "INHOUSE"),
                    ("ECO", "ECO"),
                    ("BC", "BLUE CROWN"),
                    ("FLOAT", "FLOAT"),
                    ("CUPPEN", "CUPPEN"),
                    ("ALAQUA", "ALAQUA"),
                    ("BSF_LARVE", "BSF_LARVE"),
                    ("OTHERS", "OTHERS"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="feedSize",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="stocking",
            name="fishStage",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="stocking",
            name="standing",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
