# Generated by Django 5.0.6 on 2024-10-21 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('VendorId', models.IntegerField()),
                ('companyId', models.IntegerField()),
                ('branchId', models.IntegerField()),
                ('addedById', models.IntegerField()),
                ('approverId', models.IntegerField()),
                ('status', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethodId', models.IntegerField()),
                ('Fullname', models.CharField(max_length=1000)),
                ('accountNumber', models.IntegerField()),
                ('bankName', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CyptoPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethodId', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('network', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DogFeedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FI', 'Fish_Intstines'), ('CI', 'Chicken_Intestine')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FishFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('brand', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weightUnit', models.CharField(choices=[('Kg', 'Kg'), ('Ibs', 'Pounds')], max_length=5)),
                ('desc', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=100)),
                ('tableId', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('addedById', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbName', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNumber', models.IntegerField()),
                ('beneficiaryNumber', models.IntegerField()),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNumber', models.IntegerField()),
                ('itemParent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethodId', models.IntegerField()),
                ('purchaseId', models.IntegerField()),
                ('reciptNumber', models.CharField(max_length=100, null=True)),
                ('dataCreated', models.DateTimeField()),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerId', models.IntegerField()),
                ('paymentType', models.CharField(choices=[('BankTransfer', 'BT'), ('Zelle', 'Zelle'), ('Crypto', 'Crypto'), ('Cash', 'Cash')], max_length=20)),
                ('ownerType', models.CharField(choices=[('Company', 'Company'), ('User', 'User'), ('Contacts', 'Contacts'), ('Branch', 'Branch')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField()),
                ('companyBranchId', models.IntegerField()),
                ('itemTbId', models.IntegerField()),
                ('itemId', models.IntegerField()),
                ('unitCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalcost', models.IntegerField()),
                ('expensesDate', models.DateTimeField()),
                ('paymentMethodId', models.IntegerField(null=True)),
                ('media', models.CharField(max_length=4000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerType', models.CharField(choices=[('Company', 'Company'), ('User', 'User'), ('Contacts', 'Contacts'), ('Branch', 'Branch')], max_length=10)),
                ('ownerId', models.IntegerField()),
                ('creatorId', models.IntegerField()),
                ('approverId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZellePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethodId', models.IntegerField()),
                ('email_phone', models.CharField(max_length=1000)),
                ('Fullname', models.CharField(max_length=1000)),
                ('bankName', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
