# Generated by Django 5.0.6 on 2024-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogfeedmaterial',
            name='companyBranchId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogfeedmaterial',
            name='companyId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishfeed',
            name='companyBranchId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishfeed',
            name='companyId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
