# Generated by Django 5.0.6 on 2024-10-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_address_company_contacts_relationshiplink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='RelationshipLink',
        ),
    ]
