# Generated by Django 5.0.6 on 2024-10-21 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_delete_address_delete_company_delete_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('creatorId', models.IntegerField()),
                ('approverId', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('contactName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('creatorId', models.IntegerField()),
                ('approverId', models.IntegerField()),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('dataCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('creatorId', models.IntegerField()),
                ('approverId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerType', models.CharField(choices=[('Company', 'Company'), ('User', 'User'), ('Contacts', 'Contacts'), ('Branch', 'Branch')], max_length=10)),
                ('ownerId', models.IntegerField()),
                ('relationType', models.CharField(choices=[('User', 'User'), ('Contacts', 'Contacts')], max_length=10)),
                ('relationId', models.IntegerField()),
                ('relationDetails', models.CharField(max_length=1000)),
                ('addedById', models.IntegerField()),
                ('dateAddded', models.DateTimeField(default=datetime.datetime.now)),
                ('approverId', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
