# Generated by Django 5.0.6 on 2024-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_address_company_contacts_relationshiplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
