# Generated by Django 5.1.1 on 2024-10-22 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_authority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authority",
            old_name="branchId",
            new_name="userId",
        ),
        migrations.AddField(
            model_name="authority",
            name="approverId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="authority",
            name="authorityGranted",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="authority",
            name="requestedId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
