# Generated by Django 5.1.1 on 2024-10-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authority",
            name="userId",
        ),
    ]
