# Generated by Django 5.1.1 on 2024-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0012_alter_fishfeed_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishfeed",
            name="brand",
            field=models.CharField(
                choices=[
                    ("blc", "Blue Crown"),
                    ("eco", "Eco Float"),
                    ("cupen", "Cupen"),
                ],
                max_length=10,
            ),
        ),
    ]
