# Generated by Django 5.1.1 on 2024-10-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0013_alter_fishfeed_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishfeed",
            old_name="weight",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="fishfeed",
            name="weightUnit",
        ),
        migrations.AddField(
            model_name="fishfeed",
            name="unit",
            field=models.CharField(
                choices=[("Kg", "Kg"), ("Ibs", "Pounds"), ("Bag", "Bag")],
                default="Bag",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
