# Generated by Django 5.1.1 on 2024-10-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0015_alter_fishfeed_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="paymentMethodId",
            new_name="paymentDetailsId",
        ),
    ]
