# Generated by Django 5.1.1 on 2024-11-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0016_rename_paymentmethodid_purchase_paymentdetailsid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="workEmail",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="workPhone",
        ),
    ]
