# Generated by Django 5.1.1 on 2024-10-18 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laying",
            name="batchId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bsf.batch"
            ),
        ),
    ]
