# Generated by Django 5.1.1 on 2024-10-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="laying",
            name="harvest_uom",
            field=models.CharField(
                choices=[("g", "grams"), ("Kg", "Kilo gram"), ("Ibs", "Pounds")],
                default="g",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laying",
            name="harveststatus",
            field=models.CharField(
                choices=[
                    ("N", "Not Started"),
                    ("IP", "InProgress"),
                    ("C", "Completed"),
                    ("D", "Delayed"),
                ],
                default="N",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="laying",
            name="layingEnd",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="laying",
            name="layingStart",
            field=models.DateField(),
        ),
    ]
