# Generated by Django 5.1.1 on 2024-10-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0002_laying_harvest_uom_alter_laying_harveststatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchNumber", models.IntegerField()),
                ("netNumber", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Empty"),
                            ("NR", "Need Repair"),
                            ("IU", "In USE"),
                            ("NC", "Need Cleaning"),
                        ],
                        max_length=2,
                    ),
                ),
                ("eggiesSetDate", models.DateField()),
                ("eggiesRemovedDate", models.DateField()),
                (
                    "eggiesHarvested",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
