# Generated by Django 5.1.1 on 2024-10-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0003_netstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="netstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("E", "Empty"),
                    ("NR", "Need Repair"),
                    ("IU", "In USE"),
                    ("HC", "Harvest Completed"),
                    ("NC", "Need Cleaning"),
                ],
                max_length=2,
            ),
        ),
    ]
