# Generated by Django 5.1.1 on 2024-10-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0004_alter_netstatus_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmId", models.IntegerField()),
                ("containerName", models.CharField(max_length=100)),
                (
                    "containerType",
                    models.CharField(
                        choices=[
                            ("CP", "Concrete Pond"),
                            ("PC", "Plastic Container"),
                            ("RT", "Rubber Tire"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
