# Generated by Django 5.1.1 on 2024-10-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0005_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="containerUse",
            field=models.CharField(
                choices=[
                    ("I", "Incubator"),
                    ("N", "Nursery"),
                    ("GO", "Grow Out"),
                    ("M", "Mutiple"),
                ],
                default="M",
                max_length=5,
            ),
        ),
    ]
