# Generated by Django 5.1.1 on 2024-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0006_container_containeruse"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NetStatus",
            new_name="NetStat",
        ),
    ]
