# Generated by Django 5.1.1 on 2024-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0007_rename_netstatus_netstat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batchNumber", models.IntegerField()),
                ("containerNumber", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Empty"),
                            ("NR", "Need Repair"),
                            ("IU", "In USE"),
                            ("HC", "Harvest Completed"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "harveststage",
                    models.CharField(
                        choices=[
                            ("E", "Empty"),
                            ("NR", "Need Repair"),
                            ("IU", "In USE"),
                            ("HC", "Harvest Completed"),
                        ],
                        max_length=2,
                    ),
                ),
                ("setDate", models.DateField()),
                ("removedDate", models.DateField()),
                ("harvestWeight", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
