# Generated by Django 5.1.1 on 2024-10-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0010_alter_containerstat_harveststage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerstat",
            name="harvestWeight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="netstat",
            name="eggiesHarvested",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
