# Generated by Django 5.1.1 on 2024-10-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0011_alter_containerstat_harvestweight_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Incubation",
        ),
    ]
