# Generated by Django 5.1.1 on 2024-10-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0012_delete_incubation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GrowOut",
        ),
        migrations.DeleteModel(
            name="GrowOutPond",
        ),
        migrations.DeleteModel(
            name="Incubator",
        ),
        migrations.RemoveField(
            model_name="laying",
            name="batchId",
        ),
        migrations.DeleteModel(
            name="Maturity",
        ),
        migrations.DeleteModel(
            name="MaturityPond",
        ),
        migrations.DeleteModel(
            name="Nursery",
        ),
        migrations.DeleteModel(
            name="NurseryPond",
        ),
        migrations.DeleteModel(
            name="Laying",
        ),
    ]
