# Generated by Django 5.1.1 on 2024-10-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0013_delete_growout_delete_growoutpond_delete_incubator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerstat",
            name="approverId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="containerstat",
            name="leadId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
