# Generated by Django 5.1.1 on 2024-10-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0014_containerstat_approverid_containerstat_leadid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerstat",
            name="approverId",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="containerstat",
            name="harveststage",
            field=models.CharField(
                choices=[
                    ("1", "First Insta"),
                    ("2", "Second Insta"),
                    ("5", "Fifth Insta"),
                    ("6", "PrePupa"),
                    ("7", "Pupa"),
                    ("0", "N/A"),
                ],
                default="0",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="containerstat",
            name="removedDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="containerstat",
            name="setDate",
            field=models.DateField(null=True),
        ),
    ]
