# Generated by Django 5.1.1 on 2024-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0015_alter_containerstat_approverid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerstat",
            name="leadId",
            field=models.IntegerField(null=True),
        ),
    ]
