# Generated by Django 5.1.1 on 2024-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0017_staffcurrent_stafforgchart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tableName", models.CharField(max_length=100)),
                ("farmId", models.IntegerField(null=True)),
                (
                    "view",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "add",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "edit",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "delete",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "accept",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "approve",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
