# Generated by Django 5.1.1 on 2024-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0018_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcurrent",
            name="creatorSaffId",
            field=models.IntegerField(null=True),
        ),
    ]
