# Generated by Django 5.1.1 on 2024-11-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsf", "0019_alter_staffcurrent_creatorsaffid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcurrent",
            name="level",
            field=models.CharField(
                choices=[
                    ("One", 1),
                    ("Two", 2),
                    ("Three", 3),
                    ("Four", 4),
                    ("Five", 5),
                ],
                default=1,
                max_length=5,
            ),
        ),
    ]
