# Generated by Django 5.1.1 on 2024-10-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="addedById",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
