# Generated by Django 5.0.6 on 2024-10-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='view',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5, max_length=1),
        ),
    ]
