# Generated by Django 5.1.1 on 2024-10-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0002_staff_addedbyid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffcurrent",
            name="creatorSaffId",
        ),
    ]
