# Generated by Django 5.0.6 on 2024-10-22 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0002_staffcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000, null=True)),
                ('companyId', models.IntegerField()),
                ('createdDate', models.DateField(default=datetime.datetime.now)),
                ('creatorId', models.IntegerField()),
                ('approverId', models.IntegerField()),
                ('contactName', models.CharField(max_length=100, null=True)),
                ('contactPhone', models.BigIntegerField(null=True)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('A', 'Active'), ('PA', 'pendingApproval'), ('IA', 'InActive')], default='IA', max_length=2)),
                ('comments', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
