# Generated by Django 5.1.1 on 2024-10-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0002_alter_staff_userid"),
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staffs",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.profile",
                    ),
                ),
                ("companyId", models.IntegerField()),
            ],
            bases=("users.profile",),
        ),
    ]
