# Generated by Django 5.1.1 on 2024-10-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0003_staffs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staffs",
        ),
    ]
