# Generated by Django 5.0.6 on 2024-10-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0003_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='contactEmail',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='contactName',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='contactPhone',
        ),
        migrations.AddField(
            model_name='farm',
            name='addressId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='contactId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
