# Generated by Django 5.0.6 on 2024-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0004_remove_farm_contactemail_remove_farm_contactname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='ownerType',
            field=models.CharField(choices=[('User', 'User'), ('Contacts', 'Contacts')], default='Contacts', max_length=10),
            preserve_default=False,
        ),
    ]
