# Generated by Django 5.1.1 on 2024-10-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0005_remove_staffcurrent_creatorsaffid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffcurrent",
            name="staffId",
        ),
    ]
