# Generated by Django 5.0.6 on 2024-10-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishfarm', '0005_farm_ownertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='ownerType',
            field=models.CharField(choices=[('User', 'User'), ('Staff', 'Staff'), ('Contacts', 'Contacts')], max_length=10),
        ),
    ]
