# Generated by Django 5.1.1 on 2024-10-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0006_remove_staffcurrent_staffid"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcurrent",
            name="creatorSaffId",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffcurrent",
            name="staffId",
            field=models.IntegerField(default=0),
        ),
    ]
