# Generated by Django 5.1.1 on 2024-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0007_staffcurrent_creatorsaffid_staffcurrent_staffid"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcurrent",
            name="stafId",
            field=models.IntegerField(default=0),
        ),
    ]
