# Generated by Django 5.1.1 on 2024-10-22 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0011_delete_staffcurrent"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffCurrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creatorSaffId", models.IntegerField()),
                ("approvalSaffId", models.IntegerField(null=True)),
                ("position", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        default=1,
                        max_length=10,
                    ),
                ),
                ("pay", models.DecimalField(decimal_places=3, max_digits=25)),
                ("farmId", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("F", "Fired"),
                            ("R", "Resigned"),
                            ("RT", "Retired"),
                            ("OS", "OfferSent"),
                            ("PA", "pendingApproval"),
                            ("IA", "InActive"),
                        ],
                        default="IA",
                        max_length=2,
                    ),
                ),
                ("dataCreated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "eventOccuredDate",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("comments", models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
