# Generated by Django 5.1.1 on 2024-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0012_staffcurrent"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcurrent",
            name="staffId",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
