# Generated by Django 5.1.1 on 2024-10-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0013_staffcurrent_staffid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
