# Generated by Django 5.1.1 on 2024-10-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishfarm", "0014_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ponds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("farmId", models.IntegerField()),
                (
                    "materialType",
                    models.CharField(
                        choices=[
                            ("EP", "Earthen Pond"),
                            ("CP", "Concrete Pond"),
                            ("TP", "Tampoline Pond"),
                            ("PP", "Plastic Pond"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "UOM",
                    models.CharField(
                        choices=[("FT", "Feet"), ("MT", "Meter")], max_length=3
                    ),
                ),
                ("depth", models.IntegerField()),
                ("lenght", models.IntegerField()),
                ("width", models.IntegerField()),
            ],
        ),
    ]
